### ISSUE TITLE
Send to Topic?

### ISSUE THREAD

**Issue by amouly** [nandarustam/fcm-push#1]
Any way to send messages to an specific Topic? I don't see this in the official documentation either. Thanks.

**Comment by nandarustam** [comment]
Hi there, well this module still only covers the very basic functionality of FCM, I wrote it because I my self need it in my own project. I might write the Topic functionality in the future when it's finally needed in my project. Meanwhile, feel free to write and contribute. Thanks 🍻

**Comment by ans-4175** [comment]
I try to implement send topic, @amouly would you like check this https://github.com/nandarustam/fcm-push/pull/6 out
