### ISSUE TITLE
Android action buttons payload

### ISSUE THREAD

**Issue by rapitivo** [nandarustam/fcm-push#11]
How to send action buttons on notification like this http://i.stack.imgur.com/24I2x.png?

**Comment by misugijunz** [comment]
Hi @rapitivo 

Here is the idea.

Please check
https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support. To set up data/notification you need, eg: style type in the data. You process it and show the custom notification.

Basically, you need to override current notification as a custom. Here is the link to give you the idea: http://codeversed.com/expandable-notifications-android/. It is based on older API, then you might need to find a newer way to do it. Hope it helps

**Comment by rapitivo** [comment]
Thank you @misugijunz 
My mistake was that I can not send the "notification" on the payload, only the "data".

Thanks
