### ISSUE TITLE
It's not worked, when i deploy on server.

### ISSUE THREAD

**Issue by anujtech46** [nandarustam/fcm-push#16]
it's show error.
return new Promise((resolve, reject) =>{
                                          ^
SyntaxError: Unexpected token >

**Comment by misugijunz** [comment]
Please check if your machine supports "Arrow Function"

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by ans-4175** [comment]
@misugijunz would it be better if you add babel transpiler if you want to use ES6 syntax. But IMHO, you could change it to standard function syntax.

**Comment by misugijunz** [comment]
@ans-4175 I'll check for it tonite. Thanks.

**Comment by ans-4175** [comment]
@misugijunz fixed on my last PR

**Comment by anujtech46** [comment]
Ok, I will check and inform you.

**Comment by ans-4175** [comment]
was it solved @anujtech46 ? please change it to closed, if it was

**Comment by misugijunz** [comment]
@anujtech46 we close this. If you think this case isn't resolved, then you can reopen

**Comment by ans-4175** [comment]
why it's still open, any problem?

**Comment by anujtech46** [comment]
sorry, i forget to close it.
