### ISSUE TITLE
No error on invalid to-token

### ISSUE THREAD

**Issue by TorgeirCook** [nandarustam/fcm-push#19]
Hi,

I get no errors when sending message with an invalid to-token (tested with both callback and promise). 

message : 
`
{
    to: 'invalid-token',
    data: {
      your_custom_data_key: 'your_custom_data_value'
    },
    priority: 'high',
    content_available: true,
    notification: {
      title: 'Title of your push notification',
      body: 'Body of your push notification'
    }
  }
`

**Comment by ans-4175** [comment]
I already made PR for this bug, here https://github.com/nandarustam/fcm-push/pull/20

**Comment by ans-4175** [comment]
I think we should make testcase for these lot cases

**Comment by ans-4175** [comment]
Already merged in new version

**Comment by TorgeirCook** [comment]
Tested and now works, thanks a lot!

**Comment by ans-4175** [comment]
You could close the issue
