### ISSUE TITLE
No error, no response

### ISSUE THREAD

**Issue by morfie78** [nandarustam/fcm-push#22]
I'm initializing correctly with: var fcm = new FCM(mykeyhere);
That returns a pretty object that looks correct.

Later in the story, I do a:
```
        var fcmMessage = {
          to: [ channel ],
          data: {
            "content-available": 1,
            attachment_id: idgoeshere,
          },
          notification: {
            title: 'New attachment',
            body: "Message goes here"
          }
        };
```

followed up by a:

```
        fcm.send(fcmMessage, function(error, response){
          if (error) {
            return console.error("error while sending", channel, "push notification", error);
          } else {
            console.log("sent to fcm", channel, "with response", response);
          }
        });
```

The log shows that response is "sent to fcm channelhere with response null".

If the fcm object initializes correctly, and there is no error in the fcm.send callback, why is response null?
What is the disconnect?
Thanks.

**Comment by morfie78** [comment]
As an update, I copy-pasted the example on the fcm-push main page, put in my key and change the message = {} slightly.  Same 'null' success response:

```
var FCM = require('fcm-push');

var serverKey = '';
var fcm = new FCM('*********');

var message = {
    to: '***************', // required fill with device token or topics
    data: {
        "content-available": 1,
        attachment_id: 'tango',
    },
    notification: {
        title: 'Title of your push notification',
        body: 'Body of your push notification'
    }
};

//callback style
fcm.send(message, function (err, response) {
    if (err) {
        console.log("Something has gone wrong!");
    } else {
        console.log("Successfully sent with response: ", response);
    }
});
```

**Comment by jailandrade** [comment]
Same problem here, when the message is sent the response is null

**Comment by morfie78** [comment]
After much research, I found the issue.  I was sending to a Firebase topic (not a device token).  So my 'to' field in my message needed to be prefixed with "/topics".    Instead of "channel_name" I changed it to "/topics/channel_name" and it worked.

Postmortem: This should be detected and the error messaging should be improved, or the docs themselves should be improved.

**Comment by misugijunz** [comment]
@morfie78 do you think the detection should be as feature of this npm or as firebase doc/feature?

**Comment by morfie78** [comment]
I think it would be a nice thing for the docs on this npm to add this note, in order to avoid issues like this in the future.
