### ISSUE TITLE
Undefined Variable issue in fcm push 1.1.0

### ISSUE THREAD

**Issue by haneefatel** [nandarustam/fcm-push#23]
There are two variables `anyFail` & `anySuccess ` which not declared but used in `lib/fcm.js` (line 73-83). I found it is fixed in latest master branch but we are not able to get it via npm install since valid install targets are 1.1.0, 1.0.7, 1.0.6, 1.0.5, 1.0.3, 1.0.2, 1.0.1, 1.0.0 

How can we install fcm-push 1.1.2 via npm install? Please find the fcm-push code below

                    `anyFail = ((JSON.parse(data)).failure > 0);

                        if (anyFail) {
                            error = data.substring(0).trim();
                        }

                        anySuccess = ((JSON.parse(data)).success > 0);

                        if (anySuccess) {
                            id = data.substring(0).trim();
                        }`

**Comment by ans-4175** [comment]
Can't, publisher (@nandarustam) should publish it to registry as it is

**Comment by nandarustam** [comment]
Hi folks, just published 1.1.2.
Very much thanks Mas @ans-4175 for being such a huge help to this fcm module. 
Me so sorry for being less helpful, will try my best 🙏

**Comment by haneefatel** [comment]
Thank you @nandarustam!!!
