### ISSUE TITLE
Send to Array of tokens

### ISSUE THREAD

**Issue by pentarex** [nandarustam/fcm-push#27]
Hi is it possible to send to multiple tokens at once, most of the time the users are logging in from multiple devices ios, ipad, android and so on, I was wondering is it possible to send the notification to multiple tokens at once. Or on fcm.send(messages[]....)
The problem now is after sending the notification I am saving it to mongodb, but with that logic I have to create some kind of a promise to see when all of them are send then to save it to the database

**Comment by ethan37** [comment]
Need this too.

**Comment by ethan37** [comment]
https://firebase.google.com/docs/cloud-messaging/http-server-ref

Apparently this issue is at Firebase level, so not much we can do about it...
What we can do, however, is group all the tokens in an array and loop through it executing FCM.send() on every different token.

**Comment by ethan37** [comment]
@pentarex after looking into it i can assume you can use the "registratoion_ids" JSON object key instead of the "to" key to send a multicast message to an array of tokens ! 
https://developers.google.com/cloud-messaging/http-server-ref This is GCM documentation but also works with FCM.

Can we close this?

:)

**Comment by Pradeepraj** [comment]
Using "registration_ids" instead of "to" works fine. I have tested it. 
Its also mentioned in the firebase documentation. Its safe to assume that this issue can be closed.
https://firebase.google.com/docs/cloud-messaging/http-server-ref

Thank You

**Comment by pentarex** [comment]
I thank you :)
