### ISSUE TITLE
Server-key not authorized to send messages

### ISSUE THREAD

**Issue by MooUser** [nandarustam/fcm-push#28]
Hi everybody, i'm testing _"fcm-push"_ trying to send a message to my app.
In my test.js (where i call the fcm.send function) i've got the "Invalid server response error".
Also, in the _fcm.js_ , by printing on the console.log the data i've received, i read: "Invalid (legacy) Server-key delivered or Sender is not authorized to perform request" - Error 401.

What's going on? 
I've tried all the keys i've found on Firebase Console Settings section and also the api Key i have in my google-services.json file. 

Any help would be appreciated. 
Thanks!

**Comment by ethan37** [comment]
@MooUser Hey, looks like you're using the old legacy server key which was supported by GCM and FCM too in the beginning, but maybe now it's not working anymore.. anyway you gotta try switching to the new FCM server key

**Comment by MooUser** [comment]
Sorry, i'm late: you were right, it was fine. I'm closing this post.
