### ISSUE TITLE
Push notification not working in IOS after production and in ad hoc testing.

### ISSUE THREAD

**Issue by samps01** [nandarustam/fcm-push#29]
My app is using cordova fcm plugin. FCM Push notifications work perfectly fine in development in ios. But no Push Notifications are received in production (Ad hoc and Distribution).
The token generated in null. I have rechecked all my certificates and provision profiles, all are fine. I have Push Notifications, key sharing and remote notifications enabled in capabilities in xcode. I am not sure what I am missing out. 

Thanks.

**Comment by misugijunz** [comment]
Are you using this: https://github.com/fechanique/cordova-plugin-fcm

if yes, then you can try to ask on that Github page. What I saw he doesn't used this module as its dependency since it is a node module as well.
