### ISSUE TITLE
Message data field key rejection leading to InvalidServerResponse

### ISSUE THREAD

**Issue by usalinksystem** [nandarustam/fcm-push#34]
The `data` parameter of the message to send contained the key `from` that caused a rejection and `InvalidServerResponse` error.

The message was scrubbed until the culprit `from` was identified. Once removed, the notification was successfully sent.

If this is reproducible, the library should either scrub blacklisted keywords (i.e. assuming there may be other keywords causing the same behavior) or the documentation should point to keywords to avoid including the `data` parameter of messages.

Here is a sample script:

```
var FCM = require('fcm-push');
var serverKey = $KEY;
var fcm = new FCM(serverKey);

var message = {
    to: $DEVICE_TOKEN, // required fill with device token or topics
    data: {
        from: 'bar'
    },
    notification: {
        title: 'foo',
        body: 'bar'
    }
};

//callback style
fcm.send(message, function(err, response){
    if (err) {
        console.log(err)
        console.log("Something has gone wrong!");
    } else {
        console.log("Successfully sent with response: ", response);
    }
});
```

with sample response: 
```
InvalidServerResponse
Something has gone wrong!
```

**Comment by jlcvp** [comment]
as seen on the [Official FCM Reference](https://firebase.google.com/docs/cloud-messaging/http-server-ref#send-downstream)

> The key should not be a reserved word ("from" or any word starting with "google" or "gcm"). Do not use any of the words defined in this table (such as collapse_key).
