### ISSUE TITLE
MismatchedSenderId

### ISSUE THREAD

**Issue by SharanyaRao91** [nandarustam/fcm-push#37]
Can someone please shed light on the mismatchedsenderId issue.

Getting an error:  MismatchSenderId

var registrationId = ‘Valid device token’

        var message = {
            to: registrationId,
            collapse_key:’OUR BUNDLE ID << DONT KNOW WHAT THIS IS SUPPOSED TO BE',
            notification: {
                title: 'Title of the notification',
                    body: 'Body of the notification'
            }
        };

        fcm.send(message)
            .then(function(response){
                console.log("Successfully sent with response: ", response);
                def.resolve({Error: false, message: response})
            })
            .catch(function(err){
                console.log("Something has gone wrong!");
                def.resolve({Error: true, message: "Something has gone wrong !", error: err})
                console.error(err);
            })

![image](https://user-images.githubusercontent.com/29380959/29896476-2692d810-8dab-11e7-9b45-9446c2e8f288.png)

**Comment by kaotr** [comment]
Hi,

Is this problem solved?

**Comment by SharanyaRao91** [comment]
Yes. Thanks

**Comment by Prafful-p** [comment]
@SharanyaRao91 can you please give steps how can you solved this issue

**Comment by Prafful-p** [comment]
@kaotr No, this issue is not resolved. Can you please help me out.
