### ISSUE TITLE
Error sending a message

### ISSUE THREAD

**Issue by ysilvela** [nandarustam/fcm-push#4]
TypeError: Object #<FCM> has no method 'send'

I declare a var at the same lines as example.

**Comment by nandarustam** [comment]
Can you provide your code for further debugging? @ysilvela

**Comment by nandarustam** [comment]
Hi @ysilvela, this might relates to this bug https://github.com/nandarustam/fcm-push/pull/3.
I've patched it in 1.0.7, would you give it another try?
