### ISSUE TITLE
NotRegistered error but the message is successfully sent

### ISSUE THREAD

**Issue by antoinerousseau** [nandarustam/fcm-push#7]
``` json
{
  "multicast_id": 7497838685051704056,
  "success": 0,
  "failure": 1,
  "canonical_ids": 0,
  "results": [
    {
      "error": "NotRegistered"
    }
  ]
}
```

**Comment by nandarustam** [comment]
That just means the fcmId you provided was not registered to your target device.
Have you implemented the client side FCM?
Check this out https://firebase.google.com/docs/cloud-messaging/android/client

**Comment by antoinerousseau** [comment]
The doc says
> If it is NotRegistered, you should remove the registration ID from your server database because the application was uninstalled from the device, or the client app isn't configured to receive messages.

But the app wasn't uninstalled or anything, and actually freshly generated the token :/

**Comment by alexfoxy** [comment]
I've had an issue where when I send two notifications within a few seconds of each other to different token IDs they share the same response. 

I have tested with a token I know is correct as well as a fake one e.g. "123". The device receives the notification but both responses from FCM say "InvalidRegistration".

If I had in a 5 second timeout I get two different responses (one fail, one success) from FCM.

**Comment by antoinerousseau** [comment]
weird, did you let the firebase team know?

**Comment by alexfoxy** [comment]
Yes I have. More info about the error here with a script example: https://github.com/Saber-Tecnologias/fcm-node/issues/3

**Comment by ans-4175** [comment]
Fixed on my last PR, you could check

**Comment by Shoaib3008757** [comment]
i ma getting same error, i minuts ago notification was working perfact
but now canonical_ids":0,"results":[{"error":"NotRegistered"}]} shwing this type of error

**Comment by shubham-matale** [comment]
i too have the sa,me issue
