### ISSUE TITLE
InvalidServerResponse and send 4 times

### ISSUE THREAD

**Issue by DarrylD** [nandarustam/fcm-push#9]
Here is what I have.
```
var FCM = require('fcm-push');

var serverKey = '...-6Zmw'; //i have a legit key here
var fcm = new FCM(serverKey);

var message = {
    data: {
        your_custom_data_key: 'your_custom_data_value'
    },
    condition:"'dogs' in topics || 'cats' in topics",
    notification: {
        title: 'Title of your push notification',
        body: 'Body of your push notification'
    }
};

fcm.send(message, function(err, response){
    if (err) {
        console.log("Something has gone wrong!");
        console.log(err)
    } else {
        console.log("Successfully sent with response: ", response);
    }
});
```

Every time i run this, it sends me an error, but on my client 4 messages come in.

Anything that may result in this?

**Comment by pawangspandey** [comment]
Same issue.

**Comment by DarrylD** [comment]
@pawangspandey i spun up a simple solution for my problem, maybe it can help you. https://github.com/DarrylD/simple-fcm

It don't attempt to try, just fails it if the POST fails.

**Comment by lveigas** [comment]
Same issue here.
Can you please fix this or explain what we may be doing incorrectly?

Thanks.

**Comment by ans-4175** [comment]
kindly check dev branch on this project, we happened tried to fix this issue

**Comment by coloradude** [comment]
> we happened tried to fix this issue

What?

**Comment by DarrylD** [comment]
> we happened tried to fix this issue
> What?

@coloradude He worked on the issue in the dev branch...
